import type { NextPage } from "next"
import Head from "next/head"
import { RecoilRoot } from "recoil"
import ControlBar from "../components/ControlBar"
import Handle from "../components/Handle"
import Stage from "../components/Stage"
import TouchPad from "../components/TouchPad"

// 组件
// Upload
// Stage
// Cropper
// ControlBar
// Preview

// 状态
// img {w, h, nw, nh}
// cropper rect{ x, y, w, h } radius

const App = () => {
  return (
    <RecoilRoot>
      <Stage></Stage>
      <ControlBar></ControlBar>
      {/* <TouchPad></TouchPad> */}
      <Handle></Handle>
    </RecoilRoot>
  )
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <App></App>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
